jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.7-dev"
      install:
        - pip install -r requirements.dev.txt
      script:
        - pytest tests.py
    - stage: deploy
      language: node_js
      install:
        - npm i
      script:
        - sls --version