jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.7-dev"
      install:
        - pip install -r requirements.dev.txt
      script:
        - pytest tests.py
    - stage: deploy
      language: node_js
      node_js:
        - "8.10.0"
      before_install:
        - pyenv install 3.7
      install:
        - npm i
      script:
        - sls deploy --identity_arn='$IDENTITY_ARN' --sending_address='$SENDING_ADDRESS' --receiving_addresses='$RECEIVING_ADDRESSES'