language: python
python:
  - "3.7-dev"

jobs:
  include:
    # - stage: test
    #   language: python
    #   python:
    #     - "3.7-dev"
    #   install:
    #     - pip install -r requirements.dev.txt
    #   script:
    #     - pytest tests.py
    - stage: deploy
      before_install:
        - nvm install 8.10.0
      install:
        - npm i
        - export PATH=$PATH:./node_modules/serverless/bin
      script:
        - serverless deploy --identity_arn='$IDENTITY_ARN' --sending_address='$SENDING_ADDRESS' --receiving_addresses='$RECEIVING_ADDRESSES'